<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 3 / NOTE 1*

# 📝 Assignment

## 1. Portfolio

`Dot product` & `Matrix Multiplication` 을 이용하여 다음 포트폴리오의 사람별 총합을 계산하세요.
- 결과는 `res`에 list형태로 저장합니다.

|People|Name|Price|Amount|
|:-:|:-:|:-:|:-:|
|X|A|100|35|
|X|B|500|10|
|X|C|250|25|
|X|D|50|40|
|Y|A|100|-|
|Y|B|500|50|
|Y|C|250|50|
|Y|D|50|-|
|Z|A|100|-|
|Z|B|500|-|
|Z|C|250|100|
|Z|D|50|-|



In [1]:
import numpy as np

amount = [[35, 10, 25, 40], [0, 50, 50, 0], [0, 0, 100, 0]]
price = [[100], [500], [250], [50]]

res = np.dot(amount, price)
res

array([[16750],
       [37500],
       [25000]])

## 2. Norms

주어진 값 $x_0, x_1, ... x_n$ 를 element로 갖는 벡터 $v$에 대하여 

$L_1$ Norm 의 정의는 다음과 같습니다. 

$|v| = |x_0| + |x_1| + ... + |x_n|$

$L_2$ Norm 의 정의는 다음과 같습니다.

$||v|| = \sqrt {{x_0}^2 + {x_1}^2 + ... + {x_n}^2}$

이를 참조하여 주어진 벡터에 대해서 $L_2$ Norm 의 값과 $L_1$ Norm 의 값의 차이(**절대값**)를 계산하는 함수를 만드세요.



In [2]:
def NormDif(v): 
    l1_norm = np.sum(abs(v))
    l2_norm = np.sqrt(np.sum(v**2))

    return abs(l1_norm - l2_norm)

## 3. Errors



- 2개의 벡터와, error의 타입을 입력받아 그 결과값을 계산하는 함수를 작성하세요.

- 여기서 error의 타입은 `MSE`, `MAE` 2가지 입니다.



In [24]:
def error(x, y, type) :
    if type == 'MSE':
      MSE = np.square(np.subtract(x, y)).mean()
      return MSE
    elif type == 'MAE':
      MAE = np.mean(np.abs(x-y))
      return MAE

error(10, 0, 'MSE'), error(10, 0, 'MAE')

(100.0, 10.0)

# 4. Inverse

- 주어진 matrix에 대해서 inverse matrix를 계산하여 반환하는 함수를 작성하세요. 
- 이 때 inverse 계산이 불가능 한 경우 `-1` 을 반환합니다.

In [25]:
def myInverse(m) : # m = np.array()
    ans = np.linalg.inv(m)
    return ans

myInverse(np.array([[1, 3], [5, 7]]))

array([[-0.875,  0.375],
       [ 0.625, -0.125]])

# 🔥 도전과제 



다음 링크의 내용을 참조하여 **Cramer's rule**을 사용해 $x_1$, $x_2$, $x_3$의 값을 구하세요.

<https://youtu.be/6StS7VjtuGI>


$x_1$ + $2x_3$ = 6

$-3x_1$ + $4x_2$ + $6x_3$ = 30

$-x_1$ $-2x_2$ + $3x_3$ = 8



In [28]:
a = np.array([[1, 0, 2], [-3, 4, 6], [-1, -2, 3]])
# x = np.array([[x1], [x2], [x3]])
b = np.array([[6], [30], [8]])

x = np.dot(myInverse(a), b)
print(x)


[[-0.90909091]
 [ 1.63636364]
 [ 3.45454545]]
